---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - renovate/**
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  packages: read
  security-events: write

jobs:
  workflows:
    uses: casse-boubou/ha-addon-workflows/.github/workflows/stale.yaml@main
