---
name: CI

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  queue: max

env:
  USERNAME: ${{ github.repository_owner }}
  PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write


jobs:
  lint_zizmor:
    name: zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for upload-sarif (used by zizmor-action) to upload SARIF files.
      # contents: read         # Only needed for private repos. Needed to clone the repo.
      # actions: read          # Only needed for private repos. Needed for upload-sarif to read workflow run info.
    steps:
        # check out code from GitHub
        - name: Checkout repository
          uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
          with:
            persist-credentials: false
        - name: Run zizmor 🌈
          uses: zizmorcore/zizmor-action@6fc4b006235f201fdab3722e17240ab420d580e5 # v0.6.1

  lint_shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
        # check out code from GitHub
        - name: Checkout repository
          uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
          with:
            persist-credentials: false
        # check bash integrity
        - name: Run ShellCheck
          uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
          with:
            scandir: './docker'
            severity: warning
          env:
            SHELLCHECK_OPTS: -s bash

  lint_hadolint:
    name: hadolint
    runs-on: ubuntu-latest
    steps:
        # check out code from GitHub
        - name: Checkout repository
          uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
          with:
            persist-credentials: false
        # check dockerfile integrity
        - name: Run hadolint
          uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
          with:
              ignore: DL3002
              dockerfile: ./docker/Dockerfile

  lint_dockercompose:
    name: test docker-compose
    runs-on: ubuntu-latest
    steps:
        # check out code from GitHub
        - name: Checkout repository
          uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
          with:
            persist-credentials: false
        # check compose.yml integrity
        - name: Lint docker-compose.yml
          run: |
            docker compose -f docker/docker-compose.yml config --quiet




  build:
    needs:
      - lint_zizmor
      - lint_shellcheck
      - lint_hadolint
      - lint_dockercompose
    name: Build docker image
    runs-on: ubuntu-latest

    steps:
        # check out code from GitHub
        - name: Checkout repository
          uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
          with:
            persist-credentials: false

        # Set up QEMU for allow possibility to buil multi arch
        # https://github.com/docker/setup-qemu-action
        - name: Set up QEMU
          uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

        # Set up BuildKit Docker container builder to be able to build
        # multi-platform images and export cache
        # https://github.com/docker/setup-buildx-action
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

        # Login against a Docker registry except on PR
        # https://github.com/docker/login-action
        - name: Log in to the Container registry
          if: |
            github.event_name == 'push' &&
            github.triggering_actor == github.repository_owner &&
            github.ref == 'refs/heads/main'
          uses: docker/login-action@abd2ef45e78c5afb21d64d4ca52ee8550d9572c7 # v4.5.1
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ env.USERNAME }}
            password: ${{ env.PASSWORD }}

        # Extract metadata (tags, labels) for Docker
        # https://github.com/docker/metadata-action
        - name: Extract Docker metadata
          id: metadata
          uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            tags: |
              # Following TAG are for tag the branche
              type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }}
              type=raw,value=${{ github.head_ref }},enable=${{ github.event_name == 'pull_request' }}
              # Following TAG are always apply
              type=sha,prefix=sha-,format=short,enable=true
